export const testimonialsData = [
  {
    id: 1,
    name: "Sara Underwood, USA",
    imageSource: "/images/testimonials/sara.webp",
    rate: 5,
    descriptionTitle: "The SIEL team is wonderful to work with!",
    description: "They create exceptional work, diving deep into content to uncover the 'golden nuggets' of information and transforming them into compelling and engaging reels. Their communication is outstanding, with quick response times —a rare and valuable quality. I highly recommend the SIEL team and look forward to working with them again!",
  },
  {
    id: 2,
    name: "Rachman Blake, USA",
    imageSource: "/images/testimonials/rachman.webp",
    rate: 5,
    descriptionTitle: "SIEL is a true magician when it comes to video production!",
    description: "Not only do they handle all of our last-minute changes and requests with ease, but they also ensure our videos are perfectly aligned with our Facebook and Instagram scheduling needs. Their ability to turn chaos into a masterpiece is unmatched. Keep up the amazing work, SIEL!",
  },
  {
    id: 3,
    name: "Wladimir Chapiro, UAE",
    imageSource: "/images/testimonials/wladimir.webp",
    rate: 5,
    descriptionTitle: "It was an absolute pleasure working with them, and I highly recommend their exceptional skills.",
    description: "If you're looking to elevate your online presence, I highly recommend enlisting the expertise of this digital marketing team. Skilled in social media and SEO, they are well-versed in the latest trends and strategies to help you boost your brand's visibility and connect with your target audience.",
  },
  {
    id: 4,
    name: "Emanuele Pedrona, Italy",
    imageSource: "/images/testimonials/emanuele.webp",
    rate: 5,
    descriptionTitle: "Exceptional work-we're happy to work with SIEL.",
    description: "SIEL did an outstanding job building our social presence and preparing support materials, including images, videos, and texts. The content was excellent and aligned with our goals. They were highly available and also managed LinkedIn outreach for our sales activities. A truly great professional team.",
  },
  {
    id: 5,
    name: "Ariel Tang, Hong Kong",
    imageSource: "/images/testimonials/ariel.webp",
    rate: 5,
    descriptionTitle: "They are amazing!",
    description: "They provided invaluable support during a critical transition point for my business, identifying and completing important tasks I had overlooked as a busy solopreneur. They consistently offered great suggestions and maintained excellent communication throughout. Talented, organized, and efficient, they were incredibly easy to work with. I couldn't be happier with their work!",
  },
  {
    id: 6,
    name: "Boris Kivshar, Australia",
    imageSource: "/images/testimonials/boris.webp",
    rate: 5,
    descriptionTitle: "We highly recommend hiring and working with them.",
    description: "The team has been instrumental in helping us establish and grow our social media presence over the past 9 months. They are fantastic-professional, proactive, and results-driven-significantly increasing our social following and presence in an organic and impactful way.",
  },
];
