export const headerNavigationInfo = [
  {
    id: 1,
    path: "/",
    pageName: "Home",
  },
  {
    id: 2,
    path: "",
    pageName: "Privacy Policy",
  },
];

export const privacyNavData = [
  {id: 1, color: "green", navItem: "Interpretation and Definitions", scrollTo: "interpretation-definitions", border: false},
  {id: 2, color: "black", navItem: "Interpretation", scrollTo: "interpretation", border: false},
  {id: 3, color: "black", navItem: "Definition", scrollTo: "definitions", border: true},
  {id: 4, color: "green", navItem: "Collecting and Using Your Personal Data", scrollTo: "collecting-using", border: false},
  {id: 5, color: "black", navItem: "Types of Data Collected", scrollTo: "types", border: false},
  {id: 6, color: "black", navItem: "Use of Your Personal Data", scrollTo: "use", border: false},
  {id: 7, color: "black", navItem: "Retention of Your Personal Data", scrollTo: "retention", border: false},
  {id: 8, color: "black", navItem: "Transfer of Your Personal Data", scrollTo: "transfer", border: false},
  {id: 9, color: "black", navItem: "Delete Your Personal Data", scrollTo: "delete", border: false},
  {id: 10, color: "black", navItem: "Disclosure of Your Personal Data", scrollTo: "disclosure", border: false},
  {id: 11, color: "black", navItem: "Security of Your Personal Data", scrollTo: "security", border: true},
  {id: 12, color: "green", navItem: "Additional Information", scrollTo: "additional-information", border: false},
  {id: 13, color: "black", navItem: "Children’s Privacy", scrollTo: "childrens", border: false},
  {id: 14, color: "black", navItem: "Links to Other Websites", scrollTo: "links", border: false},
  {id: 15, color: "black", navItem: "Changes to this Privacy Policy", scrollTo: "changes", border: false},
];

export const interpretationData = [
  {id: 1, text: "The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural."},
];

export const definitionData = [
  {id: 1, listItem: "<b>Account</b> means a unique account created for You to access our Service or parts of our Service."},
  {id: 2, listItem: "<b>Affiliate</b> means an entity that controls, is controlled by or is under common control with a party, where “control” means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority."},
  {id: 3, listItem: "<b>Company</b> (referred to as either “the Company”, “We”, “Us” or “Our” in this Agreement) refers to Orgaknow."},
  {id: 4, listItem: "<b>Cookies</b> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses."},
  {id: 5, listItem: "<b>Country</b> refers to: Uttar Pradesh, India."},
  {id: 6, listItem: "<b>Device</b> means any device that can access the Service such as a computer, a cellphone or a digital tablet."},
  {id: 7, listItem: "<b>Personal Data</b> is any information that relates to an identified or identifiable individual."},
  {id: 8, listItem: "<b>Service</b> refers to the Website."},
  {id: 9, listItem: "<b>Service Provider</b> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used."},
  {id: 10, listItem: "<b>Usage Data</b> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit)."},
  {id: 11, listItem: "<b>Website</b> refers to Orgaknow, accessible from <a href='https://www.orgaknow.com/' target='_blank' style='color: #138D8D;  text-decoration: none'>https://www.orgaknow.com/</a>"},
  {id: 12, listItem: "<b>You</b> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable."},
];

export const usageData = [
  {id: 1, text: "Usage Data is collected automatically when using the Service."},
  {id: 2, text: "Usage Data may include information such as Your Device’s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data."},
  {id: 3, text: "When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data."},
  {id: 4, text: "We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device."},
];

const cookieInfo = [
  [
    {id: 1, listItem: "<b>Cookies or Browser Cookies.</b> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies."},
    {id: 2, listItem: "<b>Web Beacons.</b> Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity)."},
  ],
  [
    {id: 1, text: "Cookies can be “Persistent” or “Session” Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser. You can learn more about cookies on <a href='https://www.termsfeed.com/blog/cookies/#What_Are_Cookies' target='_blank' style='color: #138D8D'>TermsFeed website</a> article."},
    {id: 2, text: "We use both Session and Persistent Cookies for the purposes set out below:"}
  ],
  [
    {id: 1, listItem: "<b>Necessary / Essential Cookies Type:</b> Session Cookies Administered by: Us Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services."},
    {id: 2, listItem: "<b>Cookies Policy / Notice Acceptance Cookies Type:</b> Persistent Cookies Administered by: Us Purpose: These Cookies identify if users have accepted the use of cookies on the Website."},
    {id: 3, listItem: "<b>Functionality Cookies Type:</b> Persistent Cookies Administered by: Us Purpose: These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website."},
  ]
];

export const cookieData = [
  {
    id: 1,
    type: "list",
    content: cookieInfo[0],
  },
  {
    id: 2,
    type: "standard",
    content: cookieInfo[1],
  },
  {
    id: 3,
    type: "list",
    content: cookieInfo[2],
  },
];

export const usePersonalData = [
  {id: 1, listItem: "<b>To provide and maintain our Service,</b> including to monitor the usage of our Service."},
  {id: 2, listItem: "<b>To manage Your Account:</b> to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user."},
  {id: 3, listItem: "<b>For the performance of a contract:</b> the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service."},
  {id: 4, listItem: "<b>To contact You:</b> To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application’s push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation."},
  {id: 5, listItem: "<b>To provide You</b> with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information."},
  {id: 6, listItem: "<b>To manage Your requests:</b> To attend and manage Your requests to Us."},
  {id: 7, listItem: "<b>For business transfers:</b> We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred."},
  {id: 8, listItem: "<b>For other purposes:</b> We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience."},
];

export const usePersonalInfoData = [
  {id: 1, listItem: "<b>With Service Providers:</b> We may share Your personal information with Service Providers to monitor and analyze the use of our Service, to contact You."},
  {id: 2, listItem: "<b>For business transfers:</b> We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company."},
  {id: 3, listItem: "<b>With Affiliates:</b> We may share Your information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners or other companies that We control or that are under common control with Us."},
  {id: 4, listItem: "<b>With business partners:</b> We may share Your information with Our business partners to offer You certain products, services or promotions."},
  {id: 5, listItem: "<b>With other users:</b> when You share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside."},
  {id: 6, listItem: "<b>With Your consent:</b> We may disclose Your personal information for any other purpose with Your consent."},
];

const personalInfo = [
  [
    {id: 1, text: "The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies."},
    {id: 2, text: "The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods."},
  ],
  [
    {id: 1, text: "Your information, including Personal Data, is processed at the Company’s operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction."},
    {id: 2, text: "Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer."},
    {id: 3, text: "The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information."},
  ],
  [
    {id: 1, text: "You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You."},
    {id: 2, text: "Our Service may give You the ability to delete certain information about You from within the Service."},
    {id: 3, text: "You may update, amend, or delete Your information at any time by signing in to Your Account, if you have one, and visiting the account settings section that allows you to manage Your personal information. You may also contact Us to request access to, correct, or delete any personal information that You have provided to Us."},
    {id: 4, text: "Please note, however, that We may need to retain certain information when we have a legal obligation or lawful basis to do so."},
  ]
];

export const personalData = [
  {
    id: 1,
    scrollId: "retention",
    content: personalInfo[0],
    title: "Retention of Your Personal Data",
  },
  {
    id: 2,
    scrollId: "transfer",
    content: personalInfo[1],
    title: "Transfer of Your Personal Data",
  },
  {
    id: 3,
    scrollId: "delete",
    content: personalInfo[2],
    title: "Delete Your Personal Data",
  },
];

export const securityData = [
  {id: 1, text: "The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security."},
];

const additionalData = [
  [
    {id: 1, text: "Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers."},
    {id: 2, text: "If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent’s consent before We collect and use that information."},
  ], 
  [
    {id: 1, text: "Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party’s site. We strongly advise You to review the Privacy Policy of every site You visit."},
    {id: 2, text: "We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services."},
  ],
  [
    {id: 1, text: "We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page."},
    {id: 2, text: "We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the “Last updated” date at the top of this Privacy Policy."},
    {id: 3, text: "You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page."},
  ]
];

export const additionalInfo = [
  {
    id: 1,
    type: "standard",
    scrollId: "childrens",
    content: additionalData[0],
    title: "Children’s Privacy",
  },
  {
    id: 2,
    type: "standard",
    scrollId: "links",
    content: additionalData[1],
    title: "Links to Other Websites",
  },
  {
    id: 3,
    type: "standard",
    scrollId: "changes",
    content: additionalData[2],
    title: "Changes to this Privacy Policy",
  },
];